apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: b204wucj4-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-8339fdd1c9.1710.p3.openshiftapps.com/rhtap/rhtap-qe-python:cf5b143592860da814c9c0dc5661750ce5bb0b02@sha256:ed164470e80382317f9e967b20cd458e92d000d811a0e63a81094889e4d3299c
          name: container-image
